run:
  deadline: 240s
  tests: false
  skip-dirs:
    - vendor
    - test

linters:
  enable-all: true

  disabled-linters:
    - interfacer
    - golint
    - scopelint
    - maligned
  disable:
    - exhaustivestruct
    - gochecknoinits
    - gci
    - maligned
    - gofumpt
    - gochecknoglobals
    - testpackage
    - wsl
    - godot
    - deadcode
    - gomnd
    - godox
    - unused
    - paralleltest
    - nlreturn
    - nestif
    - ireturn
    - lll
    - goerr113
