bot:
  discord:
    dcbottoken: "YOUR_DISCORD_BOT_TOKEN"
    dcguildid: "YOUR_DISCORD_GUILD_ID"
    botreportchannel: "YOUR_DISCORD_CHANNEL_ID_FOR_BOT_REPORTING"

maxconcurrentinstances: 1
maxlifetimeseconds: 3600

provider:
  vultr:
    apikey: "YOUR_VULTR_API_KEY"
